install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("RColorBrewer")
install.packages("topicmodels")
install.packages("twitteR")
install.packages("tm")
install.packages("wordcloud")
install.packages("NLP")
install.packages("ggplot2")
install.packages("tidytext")

